### ISSUE TITLE
Invalid Image

### ISSUE THREAD

**Issue by alex-cantor** [IATechEd/IATech#6]
Johnlee's photo is messed up.

Additionally, his LinkedIn tag is not valid... Not sure why

**Comment by Jossey28** [comment]
In the 'members.json' file, the file extension appears to be incorrect. It should not be .jpg as the image is a .png image, to fix it either convert the png file to a jpg or change the file path in 'members.json'. 

Regarding the LinkedIn tag not showing properly, there is an extra slash appended towards the end of the link, as the LinkedIn tag is obtained by getting everything after the last slash it appears as empty.

**Comment by alex-cantor** [comment]
Sounds good. Can you fix that?

Also, it seems that changes are not successfully pushing. This could just be my device. Can you take a look?

**Comment by alex-cantor** [comment]
NOTE: I made both changes, but only the image seems to be fixed. The LinkedIn tag is still broken.

Changes DO seem to be pushing.

**Comment by alex-cantor** [comment]
Fixed.

**Comment by Jossey28** [comment]
What did you do to fix it?

**Comment by alex-cantor** [comment]
You had displayed the working link in class - it had not yet updated on my machine.
